// <auto-generated />
using System;
using ArquitecturaBaseMultitenant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArquitecturaBaseMultitenant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929172034_IdentityRlsAndGrants")]
    partial class IdentityRlsAndGrants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "OccurredAtUtc", "Id");

                    b.ToTable("AuditEntries", "tenant");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Auditing.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TargetTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "OccurredAtUtc");

                    b.HasIndex("TargetTenantId", "OccurredAtUtc");

                    b.ToTable("SecurityEvents", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Authentication.LoginAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "OccurredAtUtc");

                    b.ToTable("LoginAudits", "identity");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Authentication.LoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InvalidatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Destination", "Channel", "Purpose", "ExpiresAtUtc");

                    b.ToTable("LoginCodes", "identity");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Authentication.LoginMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManagedByTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Type", "Value")
                        .IsUnique();

                    b.ToTable("LoginMethods", "identity");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Legal.LegalAcceptance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("LegalDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LegalDocumentId");

                    b.HasIndex("UserId", "LegalDocumentId")
                        .IsUnique();

                    b.ToTable("LegalAcceptances", "identity");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Legal.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "EffectiveAtUtc");

                    b.HasIndex("Kind", "Version")
                        .IsUnique();

                    b.ToTable("LegalDocuments", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Legal.LegalDocumentContent", b =>
                {
                    b.Property<Guid>("LegalDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LegalDocumentId", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("LegalDocumentContents", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAtUtc", "Id");

                    b.ToTable("OutboxMessages", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character(2)");

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasColumnType("character(3)");

                    b.Property<string>("CallingCode")
                        .HasColumnType("text");

                    b.Property<string>("DefaultCurrencyCode")
                        .HasColumnType("character(3)");

                    b.Property<string>("DefaultTimeZoneId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasColumnType("character(3)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("DefaultCurrencyCode");

                    b.HasIndex("DefaultTimeZoneId");

                    b.ToTable("Countries", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CountryTranslation", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryCode", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("CountryTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("AmDesignator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("character(2)");

                    b.Property<string>("CurrencyPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateTimePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FallbackCulture")
                        .HasColumnType("text");

                    b.Property<string>("GroupSeparator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LongDatePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PercentPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PmDesignator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TimePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("CountryCode");

                    b.HasIndex("FallbackCulture");

                    b.ToTable("Cultures", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CultureTranslation", b =>
                {
                    b.Property<string>("CultureCode")
                        .HasColumnType("text");

                    b.Property<string>("DisplayCulture")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CultureCode", "DisplayCulture");

                    b.HasIndex("DisplayCulture");

                    b.ToTable("CultureTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character(3)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinorUnits")
                        .HasColumnType("integer");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasColumnType("character(3)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Currencies", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CurrencyTranslation", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasColumnType("character(3)");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("DisplaySymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamePlural")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CurrencyCode", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("CurrencyTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TimeZones", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("character(2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ValidatorKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("CountryCode");

                    b.ToTable("TaxIdTypes", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdTypeTranslation", b =>
                {
                    b.Property<string>("TaxIdTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaxIdTypeCode", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("TaxIdTypeTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneCountry", b =>
                {
                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("TimeZoneId", "CountryCode");

                    b.HasIndex("CountryCode");

                    b.ToTable("TimeZoneCountries", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneTranslation", b =>
                {
                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TimeZoneId", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("TimeZoneTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Settings.PlatformSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountDeletionGraceDays")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessSignup")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("ConsumerSignup")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxOwnedOrganizations")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PlatformSettings", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Settings.TenantSettings", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultCulture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("character(3)");

                    b.Property<string>("DefaultTimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("DefaultCulture");

                    b.HasIndex("DefaultCurrency");

                    b.HasIndex("DefaultTimeZoneId");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSettings", "tenant");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Tenancy.Member", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("Members", "tenant");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Kind", "Status");

                    b.ToTable("Tenants", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Infrastructure.Idempotency.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TenantId", "UserId", "Key")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "UserId", "Key"), false);

                    b.ToTable("IdempotencyKeys", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("DeletionRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletionRequestedByOperatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletionScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlatformOperator")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastBusinessTenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeletionScheduledForUtc");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "platform");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "identity");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Authentication.LoginAudit", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Authentication.LoginCode", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Authentication.LoginMethod", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Legal.LegalAcceptance", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.Legal.LegalDocument", null)
                        .WithMany()
                        .HasForeignKey("LegalDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Legal.LegalDocumentContent", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.Legal.LegalDocument", null)
                        .WithMany()
                        .HasForeignKey("LegalDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Currency", null)
                        .WithMany()
                        .HasForeignKey("DefaultCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", null)
                        .WithMany()
                        .HasForeignKey("DefaultTimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CountryTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("FallbackCulture")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CultureTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("CultureCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("DisplayCulture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CurrencyTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdType", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdTypeTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdType", null)
                        .WithMany()
                        .HasForeignKey("TaxIdTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneCountry", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", null)
                        .WithMany()
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", null)
                        .WithMany()
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Settings.TenantSettings", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("DefaultCulture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Currency", null)
                        .WithMany()
                        .HasForeignKey("DefaultCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", null)
                        .WithMany()
                        .HasForeignKey("DefaultTimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Tenancy.Member", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
