// <auto-generated />
using System;
using ArquitecturaBaseMultitenant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArquitecturaBaseMultitenant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929001505_AuditSharedCounterparts")]
    partial class AuditSharedCounterparts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("platform")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "OccurredAtUtc", "Id");

                    b.ToTable("AuditEntries", "tenant");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character(2)");

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasColumnType("character(3)");

                    b.Property<string>("CallingCode")
                        .HasColumnType("text");

                    b.Property<string>("DefaultCurrencyCode")
                        .HasColumnType("character(3)");

                    b.Property<string>("DefaultTimeZoneId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasColumnType("character(3)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("DefaultCurrencyCode");

                    b.HasIndex("DefaultTimeZoneId");

                    b.ToTable("Countries", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CountryTranslation", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CountryCode", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("CountryTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("character(2)");

                    b.Property<string>("CurrencyPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateTimePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FallbackCulture")
                        .HasColumnType("text");

                    b.Property<string>("GroupSeparator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LongDatePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PercentPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TimePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("CountryCode");

                    b.HasIndex("FallbackCulture");

                    b.ToTable("Cultures", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CultureTranslation", b =>
                {
                    b.Property<string>("CultureCode")
                        .HasColumnType("text");

                    b.Property<string>("DisplayCulture")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CultureCode", "DisplayCulture");

                    b.HasIndex("DisplayCulture");

                    b.ToTable("CultureTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("character(3)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinorUnits")
                        .HasColumnType("integer");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasColumnType("character(3)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Currencies", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CurrencyTranslation", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasColumnType("character(3)");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("DisplaySymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamePlural")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CurrencyCode", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("CurrencyTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TimeZones", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("character(2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ValidatorKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("CountryCode");

                    b.ToTable("TaxIdTypes", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdTypeTranslation", b =>
                {
                    b.Property<string>("TaxIdTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaxIdTypeCode", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("TaxIdTypeTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneCountry", b =>
                {
                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("character(2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("TimeZoneId", "CountryCode");

                    b.HasIndex("CountryCode");

                    b.ToTable("TimeZoneCountries", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneTranslation", b =>
                {
                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TimeZoneId", "Culture");

                    b.HasIndex("Culture");

                    b.ToTable("TimeZoneTranslations", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Infrastructure.Idempotency.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TenantId", "UserId", "Key")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("TenantId", "UserId", "Key"), false);

                    b.ToTable("IdempotencyKeys", "platform");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "platform");
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Currency", null)
                        .WithMany()
                        .HasForeignKey("DefaultCurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", null)
                        .WithMany()
                        .HasForeignKey("DefaultTimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CountryTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("FallbackCulture")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CultureTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("CultureCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("DisplayCulture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.CurrencyTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdType", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdTypeTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.TaxIdType", null)
                        .WithMany()
                        .HasForeignKey("TaxIdTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneCountry", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", null)
                        .WithMany()
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ArquitecturaBaseMultitenant.Domain.ReferenceData.TimeZoneTranslation", b =>
                {
                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.Culture", null)
                        .WithMany()
                        .HasForeignKey("Culture")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArquitecturaBaseMultitenant.Domain.ReferenceData.ReferenceTimeZone", null)
                        .WithMany()
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
